# TODO: Split these down into logical chunks (replays, featured mods, maps, mods, ...)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: faf-content-pvc
spec:
  storageClassName: zfs-localpv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
