apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  labels:
    app: mariadb
spec:
  storageClassName: zfs-localpv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
