apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: default
  source:
    path: charts/cert-manager
    repoURL: https://github.com/Brutus5000/gitops-stack.git
    targetRevision: HEAD
    helm:
      parameters:
        - name: baseDomain
          value: {{ .Values.baseDomain }}
        - name: adminEmail
          value: {{ .Values.adminEmail }}
        - name: letsEncryptProduction
          value: {{ .Values.letsEncryptProduction | quote}}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true