apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faf-content
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/faf-content
    repoURL: https://github.com/Brutus5000/gitops-stack
    targetRevision: HEAD
    helm:
      parameters:
        - name: baseDomain
          value: {{ .Values.baseDomain }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
