apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faforever
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps/
    repoURL: https://github.com/Brutus5000/gitops-stack
    targetRevision: HEAD
    helm:
      parameters:
        - name: baseDomain
          value: {{ .Values.baseDomain }}
        - name: adminEmail
          value: {{ .Values.adminEmail }}
        - name: letsEncryptProduction
          value: {{ .Values.letsEncryptProduction | quote}}
        - name: letsEncryptProduction
          value: {{ .Values.letsEncryptProduction | quote}}
        - name: nodebb.mongodb.database
          value: {{ .Values.nodebb.mongodb.database }}
        - name: nodebb.mongodb.username
          value: {{ .Values.nodebb.mongodb.username }}