apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faforever
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps/
    repoURL: https://github.com/Brutus5000/gitops-stack
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true