apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodebb
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/nodebb
    repoURL: https://github.com/Brutus5000/gitops-stack
    targetRevision: HEAD
    helm:
      parameters:
        - name: baseDomain
          value: {{ .Values.baseDomain }}
        - name: mongodb.database
          value: {{ .Values.nodebb.mongodb.database }}
        - name: mongodb.username
          value: {{ .Values.nodebb.mongodb.username }}