traefik:
  ports:
    web:
      redirectTo: websecure

  kubernetes:
    ingressEndpoint:
      useDefaultPublishedService: true
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
