traefik:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - traefik
          topologyKey: kubernetes.io/hostname
  ports:
    web:
      redirectTo: websecure

  kubernetes:
    ingressEndpoint:
      useDefaultPublishedService: true
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
