traefik:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - traefik
          topologyKey: kubernetes.io/hostname
  ports:
    metrics:
      # When using hostNetwork, use another port to avoid conflict with node exporter:
      # https://github.com/prometheus/prometheus/wiki/Default-port-allocations
      port: 9101
    web:
      redirectTo: websecure

  metrics:
    prometheus: null

  kubernetes:
    ingressEndpoint:
      useDefaultPublishedService: true
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
