apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  labels:
    app: mongodb
spec:
  storageClassName: zfs-localpv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
