apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.baseDomain }}
  namespace: default
spec:
  commonName: {{ .Values.baseDomain }}
  secretName: {{ .Values.baseDomain }}
  dnsNames:
    - {{ .Values.baseDomain }}
    - content.{{ .Values.baseDomain }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
