apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: {{ .Values.adminEmail }}
    {{ if .Values.letsEncryptProduction }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{ else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{ end }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: traefik
