poolName: storage/faf-k8s
nodeId: nixos-k3s
zfs-localpv:
  # On NixOS, we need to declare the ZFS binary path explicitly
  zfs:
    bin: /run/current-system/sw/bin/zfs
  zfsNode:
    matchLabels: "zfs-storage"
managedStorages:
  - name: mariadb
    size: 20Gi
    accessModes: ReadWriteOnce
  - name: mongodb
    size: 20Gi
    accessModes: ReadWriteOnce
  - name: faf-content
    size: 10Gi
    accessModes: ReadWriteMany
  - name: nodebb
    size: 10Gi
    accessModes: ReadWriteMany
