apiVersion: v2
name: cert-manager
version: 1.0.0
dependencies:
  - name: cert-manager
    # Get the current versions at https://artifacthub.io/packages/helm/cert-manager/cert-manager
    version: 1.10.1 # == 1.10.1
    repository: https://charts.jetstack.io
